### ISSUE TITLE
你好，能请教一下怎么抓取pixiv登录界面的背景图吗？

### ISSUE THREAD

**Issue by onlyJinx** [mokeyjay/Pixiv-daily-top50-widget#1]
pixiv的登录背景图会几秒钟换一张，我想让我body的背景也想pixiv那样，怎么抓到那个请求的地址？fiddler看了一下不太懂…

**Comment by mokeyjay** [comment]
不好意思，你可能需要从 html/css/js 以及 fiddler 使用方法开始入门一下
