### ISSUE TITLE
挂掉了。。。

### ISSUE THREAD

**Issue by Zxilly** [mokeyjay/Pixiv-daily-top50-widget#2]
`https://i.pximg.net/c/240x480/img-master/img/2018/10/10/23/32/39/71122457_p0_master1200.jpg`
生成的图片地址报403.。。
https://zxilly.herokuapp.com/pixiv/

**Comment by mokeyjay** [comment]
你尝试着把 `$download` 打开看看？可能是P站改了防盗链机制之类的
我的 https://cloud.mokeyjay.com/pixiv 一切正常
