### ISSUE TITLE
一直卡在 排行榜更新中 请稍候

### ISSUE THREAD

**Issue by MCBBC** [mokeyjay/Pixiv-daily-top50-widget#7]
1. 香港服务器
2. 开启DEBUG后没有任何log输出
3. storage给了777权限
4. storage内除了三个空文件夹其他什么都没有
5. 最新版本

**Comment by MCBBC** [comment]
服务器可以正常Curl到pixiv的网页

**Comment by mokeyjay** [comment]
问题看起来有点古怪，你手动访问下 `/index.php?job=refresh` 看下有什么输出？

**Comment by MCBBC** [comment]
手动访问就可以用了
